services:
  - type: web
    name: netta-ultra
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn netta:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
