services:
  - type: web
    name: netta
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn netta:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
